sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build curated-data-extractor
script: docker-compose run --rm --entrypoint sh -e KBC_DATADIR=/data/ -e KBC_CONFIG_FILE=$KBC_CONFIG_FILE curated-data-extractor /code/tests.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
